app.webui/Models/ProductDetailModel.cs
using System.Collections.Generic;
using app.entity;

namespace app.webui.Models
{
    public class ProductDetailModel
    {
        public Product Product { get; set; }
        public List<Category> Categories { get; set; }
    }
}

app.webui/ViewModels/ProductViewModel.cs
using System.Collections.Generic;
using app.entity;

public class ProductListViewModel
{
    public List<Product> Products { get; set; }

}

app.webui/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using app.data.Abstract;
using app.business.Abstract;

namespace app.webui.Controllers
{
    // localhost:5000/home
    public class HomeController : Controller
    {
        private IProductService _productService;
        public HomeController(IProductService productService)
        {
            this._productService = productService;
        }
        public IActionResult Index()
        {
            var productViewModel = new ProductListViewModel()
            {
                Products = _productService.GetAll()
            };

            return View(productViewModel);
        }

        // localhost:5000/home/about
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View("MyView");
        }
    }
}

app.webui/Controllers/ShopController.cs
using System.Linq;
using app.business.Abstract;
using app.entity;
using app.webui.Models;
using Microsoft.AspNetCore.Mvc;

namespace app.webui.Controllers
{
    public class ShopController : Controller
    {
        //product service kullanmak için aşağıda inject işlemi yapıyoruz. constructor dahil.
        private IProductService _productService;
        public ShopController(IProductService productService)
        {
            this._productService = productService;
        }

        public IActionResult List(string category) //string zaten varsayılan olarak nullable
        {
            var productViewModel = new ProductListViewModel()
            {
                Products = _productService.GetProductsByCategory(category)
            };

            return View(productViewModel);
        }

        public IActionResult Details(int? id) //her zaman id gelmesi beklenmez.
        {
            if (id == null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id); // nullable değil. cast etmemiz gerek. 

            if (product == null) //gönderilen ürün bulunamadıysa
            {
                return NotFound();
            }

            //aşağıda veritabanı sorgulamayoruz, gelen değerleri gönderiyoruz.
            return View(new ProductDetailModel
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList()
            });
        }
    }
}

app.webui/ViewComponents/CategoriesViewComponent.cs
using System.Collections.Generic;
using app.business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace app.webui.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        //inject işlemi yapıyoruz aşağıda.
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            this._categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {

            if (RouteData.Values["category"] != null)
                ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_categoryService.GetAll());

        }
    }
}

app.webui/Views/Home/About.cshtml
about

app.webui/Views/Home/Index.cshtml
@model ProductListViewModel

<partial name="_header">

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">                  
            @foreach (var product in Model.Products)
            {    
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)   
                </div>       
            }           
        </div>
    </div>
</div>



@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
}

app.webui/Views/Home/MyView.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    home/contact
</body>

</html>

app.webui/Views/Product/Create.cshtml
@* action metodu olmazsa bilgiler direk controller'da buraya yönlendirilen metoda gider. *@

@* tag helperlar sayesinde model yapımızı kullandık. asp-for *@
@model Product

<form method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl" class="form-control">
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    @* <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

app.webui/Views/Product/Details.cshtml
@model Product

@section Categories
{
    @await Component.InvokeAsync("Categories")
}

<div class="card mb-3">
    <div class="card-body">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="~/img/@Model.ImageUrl" class="card-img">
            </div>
            <div class="col-md-9">
                
                    <h5 class="card-title">@Model.Name</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
            
            </div>
        </div>
    </div>
</div>

app.webui/Views/Product/Edit.cshtml
@model Product

<form method="POST">
    @* post ettiğimizde hangi id'in değiştiği bilgisini aşağıdaki hidden ile sağlıyoruz. gizli ama post ile gidiyor. *@
    <input type="hidden" name="ProductId" value="@Model.ProductId" />
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input asp-for="Price" value="@Model.Price" class="form-control">
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl" class="form-control">
    </div>
    @* <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control">
            <option selected disabled>Seçiniz</option>
        </select>
    </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

app.webui/Views/Product/Index.cshtml
@section Categories
{
    @await Component.InvokeAsync("Categories")
}


product index

app.webui/Views/Product/List.cshtml
@model ProductListViewModel


@{
    var popularClass = Model.Products.Count>2? "popular":"";
    var products = Model.Products;
}

@section Categories
{
    @await Component.InvokeAsync("Categories")
}

@if(products.Count == 0)
{
    @await Html.PartialAsync("_noproduct")
}
else
{
    <div class="row">                  
        @foreach (var product in products)
        {    
            <div class="col-md-4">
                @await Html.PartialAsync("_product", product)   
        </div>       
        }   
    </div>
}

app.webui/Views/Shared/Components/Categories/Default.cshtml
@model List<Category>

 <div class="list-group">
    <a href="/products" class="list-group-item list-group-item-action">Tüm Kategoriler</a>

    @foreach (var item in Model)
    {
        <a asp-controller="Shop" 
        asp-action="List" 
        asp-route-category="@item.Url" 
        class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == item.Url?"active":"")">
            @item.Name
        </a>
    }
</div>   

app.webui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css">
    <title>Shopapp</title>
</head>

<body>

    @await Html.PartialAsync("_navbar")

    <main class="my-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>
        </div>
    </main>

    <footer class="py-5 bg-dark text-white text-center">
        Shop App
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    @RenderSection("Scripts",false)
</body>

</html>

app.webui/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Document</title>
</head>
<body style="background-color: yellow;">

    @await Html.PartialAsync("_navbar")
    <partial name="_header">

    <main>
        <div class="container">            
            @RenderBody()
        </div>
    </main>
    
</body>
</html>

app.webui/Views/Shared/_categories.cshtml
@model List<Category>

<div class="list-group">
    @foreach (var category in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@category.Name</a>
    }
</div>

app.webui/Views/Shared/_header.cshtml
<header>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Shop App</h1>
            <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque id, eum explicabo sed
                est hic corrupti et impedit, quasi quis alias, qui provident natus enim tempore? Nesciunt repellendus
                debitis minus!</p>
        </div>
    </div>
</header>

app.webui/Views/Shared/_navbar.cshtml
  <div class="navbar bg-danger navbar-dark navbar-expand-sm">
        <div class="container">
            <a href="/" class="navbar-brand">Shopapp</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="/products" class="nav-link">Products</a>
                </li>
                 <li class="nav-item">
                    <a href="" class="nav-link">Cart</a>
                </li>
                  <li class="nav-item">
                    <a href="" class="nav-link">Orders</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="admin" asp-action="createproduct" class="nav-link">Add Product</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="admin" asp-action="productlist" class="nav-link">Admin Products</a>
                </li>
            </ul>

            <form action="/product/list" class="form-inline">
                <input name="q" type="text" class="form-control mr-2" placeholder="Search">
                <button type="submit" class="btn btn-outline-light mr-0">Search</button>
            </form>

        </div>
    </div>

app.webui/Views/Shared/_noproduct.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            Ürün yok
        </div>
    </div>
</div>

app.webui/Views/Shared/_product.cshtml
@model Product

<div class="card mb-2">
    <img class="card-img-top" src="~/img/@Model.ImageUrl" alt="">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <small class="text-muted">
            <i class="fas fa-lira-sign"></i>@Model.Price
        </small>
    </div>
    <div class="card-footer text-center">
        @* //shop controller altındaki details action metoduna gidiyor. Giderken productid bilgisini gönderiyor. *@
        <a asp-controller="shop" asp-action="Details" asp-route-id="@Model.ProductId"
            class="btn btn-primary btn-sm">Details</a>
        <a asp-controller="shop" asp-action="addtocart" asp-route-id="@Model.ProductId"
            class="btn btn-primary btn-sm">Add to Cart</a>
    </div>
</div>

app.webui/Views/Shop/Details.cshtml
@model ProductDetailModel

<div class="row">
    <div class="col-md-3">
        <img src="~/img/@Model.Product.ImageUrl" class="img-fluid">
    </div>
    <div class="col-md-9">                
            <h1 class="mb-3">@Model.Product.Name</h5> <hr>

            @foreach (var item in Model.Categories)
            {
                <a asp-controller="shop" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Name</a> 
            }                          
            
            <div class="mb-3">
                <h4 class="text-primary mb-3">
                    <i class="fas fa-lira-sign"></i>@Model.Product.Price
                </h4>
                <button type="submit" class="btn btn-primary btn-lg">Add To Cart</button>
            </h6>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p class="p-3">@Model.Product.Description</p>
    </div>
</div>

app.webui/Views/Shop/List.cshtml
@model ProductListViewModel


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
        <div class="row">                  
            @foreach (var product in Model.Products)
            {    
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)   
                </div>       
            }           
        </div>
    </div>
</div>



@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
}